import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/layout/Navbar";
import { Container } from "@mui/material";
import Footer from "@/layout/Footer";
import { Toaster } from "react-hot-toast";
import { ModalProvider } from "@/context/ModalContext";

const nunito = Nunito({
  variable: "--font-nunito",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  style: ["normal"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Pixor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} bg-[var(--background-color)] flex flex-col min-h-screen`}
      >
        <ModalProvider>
          <Toaster />
          <Navbar />
          <Container maxWidth="lg" sx={{ padding: "60px 16px 60px 16px" }}>
            {children}
          </Container>
          <Footer />
        </ModalProvider>
      </body>
    </html>
  );
}
