import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/layout/Navbar";
import { Container } from "@mui/material";
import Footer from "@/layout/Footer";

const nunito = Nunito({
  variable: "--font-nunito",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  style: ["normal"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} bg-[var(--background-color)] flex flex-col min-h-screen`}
      >
        <Navbar />
        <Container maxWidth="lg" sx={{ padding: "60px 0px 60px 0px" }}>
          {children}
        </Container>
        <Footer />
      </body>
    </html>
  );
}
